#!/bin/bash
TRUNK_ID=`wget -q http://deadlock.netbeans.org/hudson/job/trunk/rssAll -O - | tr '<>' '\n' | grep SUCCESS | head -1 | cut -d '#' -f 2 | cut -d ' ' -f 1`

mkdir -p nbbuild

cd nbbuild
rm -rf netbeans
mkdir netbeans
mkdir -p download

rm `ls download/netbeans-hudson-trunk* | grep -v $TRUNK_ID`

cd netbeans

download_and_unpack_cluster() {
    if [ ! -e ../download/netbeans-hudson-trunk-$TRUNK_ID-$1.zip ] ; then
        wget -q -N http://deadlock.netbeans.org/hudson/job/trunk/$TRUNK_ID/artifact/nbbuild/dist/zip/moduleclusters/netbeans-hudson-trunk-$TRUNK_ID-$1.zip -O ../download/netbeans-hudson-trunk-$TRUNK_ID-$1.zip || exit
    fi;
    unzip -q ../download/*$TRUNK_ID-$1.zip || exit
}

for cluster in ide platform gsf java harness nb6.0-etc; do
    download_and_unpack_cluster $cluster;
done

if [ ! -e ../download/latex.zip ] ; then
    wget -q -N http://deadlock.netbeans.org/hudson/job/latex/lastSuccessfulBuild/artifact/dist/latex.zip -O ../download/latex.zip
fi;

unzip -q ../download/latex.zip

mv latex/extra ./

rm -rf latex

cd ../..

cd nbbuild
rm -rf tmp
mkdir -p tmp
cd tmp
unpack() {
    wget -q -N http://deadlock.netbeans.org/hudson/job/nbms-and-javadoc/lastSuccessfulBuild/artifact/nbbuild/nbms/extra/$1 -O ../download/$1 || exit
    jar xf ../download/$1 netbeans || exit
}
unpack org-netbeans-modules-spellchecker-apimodule.nbm
unpack org-netbeans-modules-spellchecker.nbm
unpack org-netbeans-modules-spellchecker-dictionary_en.nbm
unpack org-netbeans-modules-spellchecker-kit.nbm
unpack org-netbeans-modules-showtodos.nbm
cp -r netbeans/* ../netbeans/extra

cd ../..

ant -Dnbplatform.temp2.harness.dir=$PWD/nbbuild/netbeans/harness -Dnbplatform.temp2.netbeans.dest.dir=$PWD/nbbuild/netbeans clean || exit
ant -Dnbplatform.temp2.harness.dir=$PWD/nbbuild/netbeans/harness -Dnbplatform.temp2.netbeans.dest.dir=$PWD/nbbuild/netbeans build-zip || exit
ant -Dnbplatform.temp2.harness.dir=$PWD/nbbuild/netbeans/harness -Dnbplatform.temp2.netbeans.dest.dir=$PWD/nbbuild/netbeans test || exit

mkdir -p build/updates
cp nbbuild/download/*.nbm build/updates

ant -Ddist.base=$DIST_BASE -Dnbplatform.temp2.harness.dir=$PWD/nbbuild/netbeans/harness -Dnbplatform.temp2.netbeans.dest.dir=$PWD/nbbuild/netbeans nbms || exit
gzip <build/updates/updates.xml >build/updates/updates.xml.gz
